### PR TITLE
align new debug method

### PR DESCRIPTION
**Pull request by taooceros**
We have changed the way of debugging in Flow, so also need to change the jsonrpc package.

By the way, why do we need the demjson?

### CODE REVIEW

**Comment by Garulf** [comment]
> We have changed the way of debugging in Flow, so also need to change the jsonrpc package.
> 
> By the way, why do we need the demjson?

I'm not entirely sure to be honest, It's being used the same as the bulit-in JSON library. It has some added functionality for linting but thats not being used as far as I can tell.

**Comment by Zeroto521** [comment]
json in standard lib can't parser some string to dict data structure, and this will raise a error.

And in temporary, I can't release any new prs until I get my acocont https://github.com/pypa/pypi-support/issues/1285

**Comment by taooceros** [comment]
> json in standard lib can't parser some string to dict data structure, and this will raise a error.

Could you gives an example? I think flow's json will be generally standard json because it is created by .net json library (which is type based).

**Comment by Zeroto521** [comment]
@taooceros detail see https://github.com/Flow-Launcher/Flow.Launcher.JsonRPC.Python/commit/aa145ff1a460d436c0ea5ac543f217a4e3bb4db5 git comment message

**Comment by taooceros** [comment]
> @taooceros detail see [aa145ff](https://github.com/Flow-Launcher/Flow.Launcher.JsonRPC.Python/commit/aa145ff1a460d436c0ea5ac543f217a4e3bb4db5) git comment message

I think it wouldn't be a issue now because we stop using a customized json parser now. We use standard .net json library so it should produce standard json.

**Review by Garulf — APPROVED** [review]

**Pull request merged**
